<?php

namespace Modules\Product\Facades;

class ProductService extends \Illuminate\Support\Facades\Facade
{
    public static function getFacadeAccessor()
    {
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
        return 'ProductService';
    }
}
