<?php

namespace Modules\User\Facades\UserService\AdminService\Administrator;

use Illuminate\Support\Facades\Facade;

class AdministratorService extends Facade
{
    public static function getFacadeAccessor()
    {
        return 'AdministratorService';
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }
}
