<?php

namespace Modules\User\Facades\InfuencerService;

use Illuminate\Support\Facades\Facade;

class InfluencerService extends Facade
{
    public static function getFacadeAccessor()
    {
        return 'InfluencerService';
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }
}
