<?php

namespace Modules\Setting\Facades;

class LanguageService extends \Illuminate\Support\Facades\Facade
{
    protected static function getFacadeAccessor()
    {
        return 'LanguageService';
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }
}
