<?php

namespace Modules\User\Facades\UserService\AdminService;

use Illuminate\Support\Facades\Facade;

class AdminService extends Facade
{
    public static function getFacadeAccessor()
    {
        return 'AdminService';
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }
}
