<?php

namespace Modules\Marketing\Facades\Offer;

use Illuminate\Support\Facades\Facade;

class OfferService extends Facade
{
    public static function getFacadeAccessor()
    {
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
        return 'OfferService';
    }
}
