<?php

namespace Modules\User\Facades\UserService\CustomerService\Normal;

use Illuminate\Support\Facades\Facade;

class NormalService extends Facade
{
    public static function getFacadeAccessor()
    {
        return 'NormalService';
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }
}
