<?php

namespace Modules\Order\Facades;

use Illuminate\Support\Facades\Facade;

class OrderService extends Facade
{
    public static function getFacadeAccessor()
    {
        return 'OrderService';
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }
}
