<?php

namespace Modules\Marketing\Facades\Coupon;

class CouponService extends \Illuminate\Support\Facades\Facade
{
    public static function getFacadeAccessor()
    {
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
        return 'CouponService';
    }
}
