<?php

namespace Modules\User\Facades\UserService;

use Illuminate\Support\Facades\Facade;

class UserService extends Facade
{
    public static function getFacadeAccessor()
    {
        return 'UserService';
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }

}
