<?php

namespace Modules\Website\Services\Blocks;

use Illuminate\Support\Str;
use Modules\Website\Enums\BlockCategoryEnum;

class AboutDSHService extends BlockService
{
    public function getActiveBlocks(string $category): array
    {
        $blocks = parent::getActiveBlocks($category); // TODO: Change the autogenerated stub
        $coreValues = parent::getActiveBlocks(Str::slug(BlockCategoryEnum::CORE_VALUES->value));
        $mission = parent::getActiveBlocks(Str::slug(BlockCategoryEnum::MISSION->value));
        $vision = parent::getActiveBlocks(Str::slug(BlockCategoryEnum::VISION->value));
        return array_merge($blocks, $coreValues, $mission, $vision);
    }
}
