<?php

namespace Modules\Website\Services\Blocks;

use Illuminate\Support\Str;
use Modules\Website\Enums\BlockCategoryEnum;

class GeneralDirectorService extends BlockService
{
    public function getActiveBlocks(string $category): array
    {
        $generalDirectorSpeech = parent::getActiveBlocks($category); // TODO: Change the autogenerated stub
        $managerProfile = parent::getActiveBlocks(Str::slug(BlockCategoryEnum::MANAGER_PROFILE->value));
        $philosophy = parent::getActiveBlocks(Str::slug(BlockCategoryEnum::LEADERSHIP_PHILOSOPHY->value));
        return array_merge($generalDirectorSpeech, $managerProfile, $philosophy);
    }
}
