<?php

namespace Modules\Website\Facades\Blocks;

use Illuminate\Support\Facades\Facade;

class BlockService extends Facade
{
    public static function getFacadeAccessor(): string
    {
        return 'BlockService';
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }
}
