<?php

namespace Modules\Product\Facades\UserProductService;

use Illuminate\Support\Facades\Facade;

class UserProductService extends Facade
{
    public static function getFacadeAccessor()
    {
        return 'UserProductService';
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }
}
