<?php


namespace Modules\Website\Facades\Menus;


use Illuminate\Support\Facades\Facade;

class MenuCategoryService extends Facade
{
    public static function getFacadeAccessor()
    {
        return 'MenuCategoryService';
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }
}
