<?php


namespace Modules\Website\Facades\Menus;


use Illuminate\Support\Facades\Facade;

class MenuService extends Facade
{
    public static function getFacadeAccessor()
    {
        return 'MenuService';
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }
}
