<?php

namespace Modules\Category\Facades;

use Illuminate\Support\Facades\Facade;

class CategoryService extends Facade
{
    protected static function getFacadeAccessor()
    {
        return 'CategoryService';
    //    parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }
}
