<?php

namespace Modules\User\Facades\UserService\CustomerService;

use Illuminate\Support\Facades\Facade;

class CustomerService extends Facade
{
    public static function getFacadeAccessor()
    {
        return 'CustomerService';
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }
}
