<?php

namespace Modules\User\Facades\UserService\CustomerService\Influencer;

use Illuminate\Support\Facades\Facade;

class InfluencerService extends Facade
{
    public static function getFacadeAccessor()
    {
        return 'InfulencerService';
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }
}
