enum BlockCategories {
    MAIN_SECTION = "Main Section",
    STORE_SECTION = "Store Section",
    SERVICES = "Services",
    CLIENTS = "Clients",
    GALLERY = "Gallery",
    ABOUT = "About Us",
    ABOUT_DSH = "About D S H",
    GENERAL_DIRECTOR_SPEECH = "General Director Speech",
    MANAGER_PROFILE = "Manager Profile",
    LEADERSHIP_PHILOSOPHY = "Leadership Philosophy",
    MISSION = "Our Mission",
    VISION = "Our Vision",
    CORE_VALUES = "Core Values",
    CONTACT_US = "Contact Us",
    NEWS = "News",
    ARTICLES = "Articles",
    INDUSTRIES = "Industries",
    PROJECTS = "Projects",
    PRINCIPAL_ACTIVITIES = "Principal Activities",
    QUALITY_ASSURANCE = "Quality Assurance",
    SAFETY_PLANNING = "Safety Planning",
    COMPANY_THOUGHTS = "Company Thoughts",
    ORGANIZATIONAL_SECTION = "Organizational Structure",
}

export default BlockCategories;
