<?php

namespace Modules\Website\Facades\Articles;

use Illuminate\Support\Facades\Facade;

class ArticleCategoryService extends Facade
{
    public static function getFacadeAccessor()
    {
        return 'ArticleCategoryService';
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }
}
