<?php

namespace Modules\Website\Services\Articles;

use Illuminate\Support\Facades\Facade;

class ArticleService extends Facade
{
    public static function getFacadeAccessor()
    {
        return 'ArticleService';
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }
}
