<?php

namespace Modules\Payment\Facades;

class PaymentService extends \Illuminate\Support\Facades\Facade
{
    public static function getFacadeAccessor()
    {
        return 'PaymentService';
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }
}
